repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        -   id: check-byte-order-marker
        -   id: check-case-conflict
        -   id: check-merge-conflict
        -   id: check-symlinks
        -   id: check-added-large-files
        -   id: check-yaml
            exclude: ".clang-format"
        -   id: detect-private-key
        -   id: name-tests-test
        -   id: end-of-file-fixer
        -   id: mixed-line-ending
        -   id: trailing-whitespace

  -   repo: local
      hooks:
        # c++ formatting
        - id: clang-format
          name: clang-format
          entry: clang-format
          pass_filenames: true
          language: system
          types: [ c++ ]
          args: [ "-i" ]

        # rust formatting
        - id: cargo-format
          name: cargo +nightly fmt
          entry: cargo +nightly fmt
          pass_filenames: false
          language: system
          types: [ rust ]

        # compiler check
        - id: cargo-check
          name: cargo check
          entry: cargo check
          pass_filenames: false
          language: system
          types: [ rust ]

        # linting
        - id: cargo-clippy
          name: cargo clippy
          entry: cargo clippy
          pass_filenames: false
          language: system
          types: [ rust ]
          args: ["--all-targets"]
